// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/highlight.dart';
import 'api/lua_script.dart';
import 'api/script.dart';
import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.13.0';

  @override
  int get rustContentHash => -1590524703;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_madedit2',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  String crateApiSimpleGreet({required String name});

  List<HlSpan> crateApiHighlightHighlight({
    required String lang,
    required String source,
  });

  Future<List<HlSpan>> crateApiHighlightHighlightOffThread({
    required String lang,
    required String source,
  });

  List<HlSpan> crateApiHighlightHighlightWasm({
    required String lang,
    required String source,
  });

  Future<List<HlSpan>> crateApiHighlightHighlightWasmOffThread({
    required String lang,
    required String source,
  });

  void crateApiHighlightHlDocClose({required PlatformInt64 id});

  Future<HlPatch?> crateApiHighlightHlDocEdit({
    required PlatformInt64 id,
    required PlatformInt64 startLine,
    required PlatformInt64 oldEndLine,
    required List<String> newLines,
  });

  List<FoldRange>? crateApiHighlightHlDocFolds({required PlatformInt64 id});

  Future<List<HlSpan>?> crateApiHighlightHlDocOpen({
    required PlatformInt64 id,
    required String lang,
    required bool wasm,
    required String source,
  });

  Future<void> crateApiSimpleInitApp();

  String? crateApiScriptJsRegisterScript({
    required String name,
    required String source,
  });

  void crateApiScriptJsRetainScripts({required List<String> names});

  String? crateApiLuaScriptLuaRegisterScript({
    required String name,
    required String source,
  });

  void crateApiLuaScriptLuaRetainScripts({required List<String> names});

  bool crateApiHighlightRegisterWasmGrammar({
    required String lang,
    required List<int> wasm,
    required String query,
  });

  void crateApiScriptScriptSessionClose({required PlatformInt64 id});

  Future<ScriptOpen> crateApiScriptScriptSessionOpen({
    required String engine,
    required String name,
  });

  Future<JsTransformOut> crateApiScriptScriptSessionTransformLines({
    required PlatformInt64 id,
    required List<String> lines,
    required PlatformInt64 firstLineNo,
  });

  Future<ScriptTextOut> crateApiScriptScriptSessionTransformText({
    required PlatformInt64 id,
    required String text,
  });

  bool crateApiHighlightSupportedLanguage({required String ext});

  bool crateApiHighlightWasmGrammarLoads({
    required String lang,
    required List<int> wasm,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  String crateApiSimpleGreet({required String name}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGreetConstMeta,
        argValues: [name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGreetConstMeta =>
      const TaskConstMeta(debugName: "greet", argNames: ["name"]);

  @override
  List<HlSpan> crateApiHighlightHighlight({
    required String lang,
    required String source,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(lang, serializer);
          sse_encode_String(source, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_hl_span,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiHighlightHighlightConstMeta,
        argValues: [lang, source],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiHighlightHighlightConstMeta =>
      const TaskConstMeta(debugName: "highlight", argNames: ["lang", "source"]);

  @override
  Future<List<HlSpan>> crateApiHighlightHighlightOffThread({
    required String lang,
    required String source,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(lang, serializer);
          sse_encode_String(source, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_hl_span,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiHighlightHighlightOffThreadConstMeta,
        argValues: [lang, source],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiHighlightHighlightOffThreadConstMeta =>
      const TaskConstMeta(
        debugName: "highlight_off_thread",
        argNames: ["lang", "source"],
      );

  @override
  List<HlSpan> crateApiHighlightHighlightWasm({
    required String lang,
    required String source,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(lang, serializer);
          sse_encode_String(source, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_hl_span,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiHighlightHighlightWasmConstMeta,
        argValues: [lang, source],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiHighlightHighlightWasmConstMeta =>
      const TaskConstMeta(
        debugName: "highlight_wasm",
        argNames: ["lang", "source"],
      );

  @override
  Future<List<HlSpan>> crateApiHighlightHighlightWasmOffThread({
    required String lang,
    required String source,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(lang, serializer);
          sse_encode_String(source, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_hl_span,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiHighlightHighlightWasmOffThreadConstMeta,
        argValues: [lang, source],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiHighlightHighlightWasmOffThreadConstMeta =>
      const TaskConstMeta(
        debugName: "highlight_wasm_off_thread",
        argNames: ["lang", "source"],
      );

  @override
  void crateApiHighlightHlDocClose({required PlatformInt64 id}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(id, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiHighlightHlDocCloseConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiHighlightHlDocCloseConstMeta =>
      const TaskConstMeta(debugName: "hl_doc_close", argNames: ["id"]);

  @override
  Future<HlPatch?> crateApiHighlightHlDocEdit({
    required PlatformInt64 id,
    required PlatformInt64 startLine,
    required PlatformInt64 oldEndLine,
    required List<String> newLines,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(id, serializer);
          sse_encode_i_64(startLine, serializer);
          sse_encode_i_64(oldEndLine, serializer);
          sse_encode_list_String(newLines, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_hl_patch,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiHighlightHlDocEditConstMeta,
        argValues: [id, startLine, oldEndLine, newLines],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiHighlightHlDocEditConstMeta => const TaskConstMeta(
    debugName: "hl_doc_edit",
    argNames: ["id", "startLine", "oldEndLine", "newLines"],
  );

  @override
  List<FoldRange>? crateApiHighlightHlDocFolds({required PlatformInt64 id}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(id, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 12)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_list_fold_range,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiHighlightHlDocFoldsConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiHighlightHlDocFoldsConstMeta =>
      const TaskConstMeta(debugName: "hl_doc_folds", argNames: ["id"]);

  @override
  Future<List<HlSpan>?> crateApiHighlightHlDocOpen({
    required PlatformInt64 id,
    required String lang,
    required bool wasm,
    required String source,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(id, serializer);
          sse_encode_String(lang, serializer);
          sse_encode_bool(wasm, serializer);
          sse_encode_String(source, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_list_hl_span,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiHighlightHlDocOpenConstMeta,
        argValues: [id, lang, wasm, source],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiHighlightHlDocOpenConstMeta => const TaskConstMeta(
    debugName: "hl_doc_open",
    argNames: ["id", "lang", "wasm", "source"],
  );

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  String? crateApiScriptJsRegisterScript({
    required String name,
    required String source,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          sse_encode_String(source, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 15)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiScriptJsRegisterScriptConstMeta,
        argValues: [name, source],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiScriptJsRegisterScriptConstMeta =>
      const TaskConstMeta(
        debugName: "js_register_script",
        argNames: ["name", "source"],
      );

  @override
  void crateApiScriptJsRetainScripts({required List<String> names}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_String(names, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 16)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiScriptJsRetainScriptsConstMeta,
        argValues: [names],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiScriptJsRetainScriptsConstMeta =>
      const TaskConstMeta(debugName: "js_retain_scripts", argNames: ["names"]);

  @override
  String? crateApiLuaScriptLuaRegisterScript({
    required String name,
    required String source,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          sse_encode_String(source, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 17)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiLuaScriptLuaRegisterScriptConstMeta,
        argValues: [name, source],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLuaScriptLuaRegisterScriptConstMeta =>
      const TaskConstMeta(
        debugName: "lua_register_script",
        argNames: ["name", "source"],
      );

  @override
  void crateApiLuaScriptLuaRetainScripts({required List<String> names}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_String(names, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 18)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiLuaScriptLuaRetainScriptsConstMeta,
        argValues: [names],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLuaScriptLuaRetainScriptsConstMeta =>
      const TaskConstMeta(debugName: "lua_retain_scripts", argNames: ["names"]);

  @override
  bool crateApiHighlightRegisterWasmGrammar({
    required String lang,
    required List<int> wasm,
    required String query,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(lang, serializer);
          sse_encode_list_prim_u_8_loose(wasm, serializer);
          sse_encode_String(query, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 19)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiHighlightRegisterWasmGrammarConstMeta,
        argValues: [lang, wasm, query],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiHighlightRegisterWasmGrammarConstMeta =>
      const TaskConstMeta(
        debugName: "register_wasm_grammar",
        argNames: ["lang", "wasm", "query"],
      );

  @override
  void crateApiScriptScriptSessionClose({required PlatformInt64 id}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(id, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 20)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiScriptScriptSessionCloseConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiScriptScriptSessionCloseConstMeta =>
      const TaskConstMeta(debugName: "script_session_close", argNames: ["id"]);

  @override
  Future<ScriptOpen> crateApiScriptScriptSessionOpen({
    required String engine,
    required String name,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(engine, serializer);
          sse_encode_String(name, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 21,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_script_open,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiScriptScriptSessionOpenConstMeta,
        argValues: [engine, name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiScriptScriptSessionOpenConstMeta =>
      const TaskConstMeta(
        debugName: "script_session_open",
        argNames: ["engine", "name"],
      );

  @override
  Future<JsTransformOut> crateApiScriptScriptSessionTransformLines({
    required PlatformInt64 id,
    required List<String> lines,
    required PlatformInt64 firstLineNo,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(id, serializer);
          sse_encode_list_String(lines, serializer);
          sse_encode_i_64(firstLineNo, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 22,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_js_transform_out,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiScriptScriptSessionTransformLinesConstMeta,
        argValues: [id, lines, firstLineNo],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiScriptScriptSessionTransformLinesConstMeta =>
      const TaskConstMeta(
        debugName: "script_session_transform_lines",
        argNames: ["id", "lines", "firstLineNo"],
      );

  @override
  Future<ScriptTextOut> crateApiScriptScriptSessionTransformText({
    required PlatformInt64 id,
    required String text,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(id, serializer);
          sse_encode_String(text, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 23,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_script_text_out,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiScriptScriptSessionTransformTextConstMeta,
        argValues: [id, text],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiScriptScriptSessionTransformTextConstMeta =>
      const TaskConstMeta(
        debugName: "script_session_transform_text",
        argNames: ["id", "text"],
      );

  @override
  bool crateApiHighlightSupportedLanguage({required String ext}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(ext, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 24)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiHighlightSupportedLanguageConstMeta,
        argValues: [ext],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiHighlightSupportedLanguageConstMeta =>
      const TaskConstMeta(debugName: "supported_language", argNames: ["ext"]);

  @override
  bool crateApiHighlightWasmGrammarLoads({
    required String lang,
    required List<int> wasm,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(lang, serializer);
          sse_encode_list_prim_u_8_loose(wasm, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 25)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiHighlightWasmGrammarLoadsConstMeta,
        argValues: [lang, wasm],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiHighlightWasmGrammarLoadsConstMeta =>
      const TaskConstMeta(
        debugName: "wasm_grammar_loads",
        argNames: ["lang", "wasm"],
      );

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  Runner dco_decode_TraitDef_Runner(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  HlPatch dco_decode_box_autoadd_hl_patch(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_hl_patch(raw);
  }

  @protected
  FoldRange dco_decode_fold_range(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return FoldRange(
      startRow: dco_decode_u_32(arr[0]),
      endRow: dco_decode_u_32(arr[1]),
    );
  }

  @protected
  HlLineSpan dco_decode_hl_line_span(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return HlLineSpan(
      line: dco_decode_u_32(arr[0]),
      start: dco_decode_u_32(arr[1]),
      end: dco_decode_u_32(arr[2]),
      style: dco_decode_u_32(arr[3]),
    );
  }

  @protected
  HlPatch dco_decode_hl_patch(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return HlPatch(
      startLine: dco_decode_i_64(arr[0]),
      endLine: dco_decode_i_64(arr[1]),
      spans: dco_decode_list_hl_line_span(arr[2]),
    );
  }

  @protected
  HlSpan dco_decode_hl_span(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return HlSpan(
      start: dco_decode_u_32(arr[0]),
      end: dco_decode_u_32(arr[1]),
      style: dco_decode_u_32(arr[2]),
    );
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  JsTransformOut dco_decode_js_transform_out(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return JsTransformOut(
      lines: dco_decode_list_String(arr[0]),
      deleted: dco_decode_list_bool(arr[1]),
      error: dco_decode_opt_String(arr[2]),
    );
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<bool> dco_decode_list_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_bool).toList();
  }

  @protected
  List<FoldRange> dco_decode_list_fold_range(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_fold_range).toList();
  }

  @protected
  List<HlLineSpan> dco_decode_list_hl_line_span(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_hl_line_span).toList();
  }

  @protected
  List<HlSpan> dco_decode_list_hl_span(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_hl_span).toList();
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  HlPatch? dco_decode_opt_box_autoadd_hl_patch(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_hl_patch(raw);
  }

  @protected
  List<FoldRange>? dco_decode_opt_list_fold_range(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_list_fold_range(raw);
  }

  @protected
  List<HlSpan>? dco_decode_opt_list_hl_span(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_list_hl_span(raw);
  }

  @protected
  ScriptOpen dco_decode_script_open(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return ScriptOpen(
      id: dco_decode_i_64(arr[0]),
      hasLine: dco_decode_bool(arr[1]),
      hasText: dco_decode_bool(arr[2]),
      error: dco_decode_opt_String(arr[3]),
    );
  }

  @protected
  ScriptTextOut dco_decode_script_text_out(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return ScriptTextOut(
      text: dco_decode_opt_String(arr[0]),
      error: dco_decode_opt_String(arr[1]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  HlPatch sse_decode_box_autoadd_hl_patch(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_hl_patch(deserializer));
  }

  @protected
  FoldRange sse_decode_fold_range(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_startRow = sse_decode_u_32(deserializer);
    var var_endRow = sse_decode_u_32(deserializer);
    return FoldRange(startRow: var_startRow, endRow: var_endRow);
  }

  @protected
  HlLineSpan sse_decode_hl_line_span(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_line = sse_decode_u_32(deserializer);
    var var_start = sse_decode_u_32(deserializer);
    var var_end = sse_decode_u_32(deserializer);
    var var_style = sse_decode_u_32(deserializer);
    return HlLineSpan(
      line: var_line,
      start: var_start,
      end: var_end,
      style: var_style,
    );
  }

  @protected
  HlPatch sse_decode_hl_patch(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_startLine = sse_decode_i_64(deserializer);
    var var_endLine = sse_decode_i_64(deserializer);
    var var_spans = sse_decode_list_hl_line_span(deserializer);
    return HlPatch(
      startLine: var_startLine,
      endLine: var_endLine,
      spans: var_spans,
    );
  }

  @protected
  HlSpan sse_decode_hl_span(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_start = sse_decode_u_32(deserializer);
    var var_end = sse_decode_u_32(deserializer);
    var var_style = sse_decode_u_32(deserializer);
    return HlSpan(start: var_start, end: var_end, style: var_style);
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  JsTransformOut sse_decode_js_transform_out(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_lines = sse_decode_list_String(deserializer);
    var var_deleted = sse_decode_list_bool(deserializer);
    var var_error = sse_decode_opt_String(deserializer);
    return JsTransformOut(
      lines: var_lines,
      deleted: var_deleted,
      error: var_error,
    );
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<bool> sse_decode_list_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <bool>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_bool(deserializer));
    }
    return ans_;
  }

  @protected
  List<FoldRange> sse_decode_list_fold_range(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <FoldRange>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_fold_range(deserializer));
    }
    return ans_;
  }

  @protected
  List<HlLineSpan> sse_decode_list_hl_line_span(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <HlLineSpan>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_hl_line_span(deserializer));
    }
    return ans_;
  }

  @protected
  List<HlSpan> sse_decode_list_hl_span(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <HlSpan>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_hl_span(deserializer));
    }
    return ans_;
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  HlPatch? sse_decode_opt_box_autoadd_hl_patch(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_hl_patch(deserializer));
    } else {
      return null;
    }
  }

  @protected
  List<FoldRange>? sse_decode_opt_list_fold_range(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_list_fold_range(deserializer));
    } else {
      return null;
    }
  }

  @protected
  List<HlSpan>? sse_decode_opt_list_hl_span(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_list_hl_span(deserializer));
    } else {
      return null;
    }
  }

  @protected
  ScriptOpen sse_decode_script_open(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_i_64(deserializer);
    var var_hasLine = sse_decode_bool(deserializer);
    var var_hasText = sse_decode_bool(deserializer);
    var var_error = sse_decode_opt_String(deserializer);
    return ScriptOpen(
      id: var_id,
      hasLine: var_hasLine,
      hasText: var_hasText,
      error: var_error,
    );
  }

  @protected
  ScriptTextOut sse_decode_script_text_out(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_text = sse_decode_opt_String(deserializer);
    var var_error = sse_decode_opt_String(deserializer);
    return ScriptTextOut(text: var_text, error: var_error);
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_hl_patch(HlPatch self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_hl_patch(self, serializer);
  }

  @protected
  void sse_encode_fold_range(FoldRange self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.startRow, serializer);
    sse_encode_u_32(self.endRow, serializer);
  }

  @protected
  void sse_encode_hl_line_span(HlLineSpan self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.line, serializer);
    sse_encode_u_32(self.start, serializer);
    sse_encode_u_32(self.end, serializer);
    sse_encode_u_32(self.style, serializer);
  }

  @protected
  void sse_encode_hl_patch(HlPatch self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.startLine, serializer);
    sse_encode_i_64(self.endLine, serializer);
    sse_encode_list_hl_line_span(self.spans, serializer);
  }

  @protected
  void sse_encode_hl_span(HlSpan self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.start, serializer);
    sse_encode_u_32(self.end, serializer);
    sse_encode_u_32(self.style, serializer);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_js_transform_out(
    JsTransformOut self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_String(self.lines, serializer);
    sse_encode_list_bool(self.deleted, serializer);
    sse_encode_opt_String(self.error, serializer);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_bool(List<bool> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_bool(item, serializer);
    }
  }

  @protected
  void sse_encode_list_fold_range(
    List<FoldRange> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_fold_range(item, serializer);
    }
  }

  @protected
  void sse_encode_list_hl_line_span(
    List<HlLineSpan> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_hl_line_span(item, serializer);
    }
  }

  @protected
  void sse_encode_list_hl_span(List<HlSpan> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_hl_span(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_hl_patch(
    HlPatch? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_hl_patch(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_list_fold_range(
    List<FoldRange>? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_list_fold_range(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_list_hl_span(
    List<HlSpan>? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_list_hl_span(self, serializer);
    }
  }

  @protected
  void sse_encode_script_open(ScriptOpen self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.id, serializer);
    sse_encode_bool(self.hasLine, serializer);
    sse_encode_bool(self.hasText, serializer);
    sse_encode_opt_String(self.error, serializer);
  }

  @protected
  void sse_encode_script_text_out(
    ScriptTextOut self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_String(self.text, serializer);
    sse_encode_opt_String(self.error, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
