// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/highlight.dart';
import 'api/lua_script.dart';
import 'api/script.dart';
import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  Runner dco_decode_TraitDef_Runner(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  HlPatch dco_decode_box_autoadd_hl_patch(dynamic raw);

  @protected
  FoldRange dco_decode_fold_range(dynamic raw);

  @protected
  HlLineSpan dco_decode_hl_line_span(dynamic raw);

  @protected
  HlPatch dco_decode_hl_patch(dynamic raw);

  @protected
  HlSpan dco_decode_hl_span(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  JsTransformOut dco_decode_js_transform_out(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<bool> dco_decode_list_bool(dynamic raw);

  @protected
  List<FoldRange> dco_decode_list_fold_range(dynamic raw);

  @protected
  List<HlLineSpan> dco_decode_list_hl_line_span(dynamic raw);

  @protected
  List<HlSpan> dco_decode_list_hl_span(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  HlPatch? dco_decode_opt_box_autoadd_hl_patch(dynamic raw);

  @protected
  List<FoldRange>? dco_decode_opt_list_fold_range(dynamic raw);

  @protected
  List<HlSpan>? dco_decode_opt_list_hl_span(dynamic raw);

  @protected
  ScriptOpen dco_decode_script_open(dynamic raw);

  @protected
  ScriptTextOut dco_decode_script_text_out(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  HlPatch sse_decode_box_autoadd_hl_patch(SseDeserializer deserializer);

  @protected
  FoldRange sse_decode_fold_range(SseDeserializer deserializer);

  @protected
  HlLineSpan sse_decode_hl_line_span(SseDeserializer deserializer);

  @protected
  HlPatch sse_decode_hl_patch(SseDeserializer deserializer);

  @protected
  HlSpan sse_decode_hl_span(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  JsTransformOut sse_decode_js_transform_out(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<bool> sse_decode_list_bool(SseDeserializer deserializer);

  @protected
  List<FoldRange> sse_decode_list_fold_range(SseDeserializer deserializer);

  @protected
  List<HlLineSpan> sse_decode_list_hl_line_span(SseDeserializer deserializer);

  @protected
  List<HlSpan> sse_decode_list_hl_span(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  HlPatch? sse_decode_opt_box_autoadd_hl_patch(SseDeserializer deserializer);

  @protected
  List<FoldRange>? sse_decode_opt_list_fold_range(SseDeserializer deserializer);

  @protected
  List<HlSpan>? sse_decode_opt_list_hl_span(SseDeserializer deserializer);

  @protected
  ScriptOpen sse_decode_script_open(SseDeserializer deserializer);

  @protected
  ScriptTextOut sse_decode_script_text_out(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_hl_patch(HlPatch self, SseSerializer serializer);

  @protected
  void sse_encode_fold_range(FoldRange self, SseSerializer serializer);

  @protected
  void sse_encode_hl_line_span(HlLineSpan self, SseSerializer serializer);

  @protected
  void sse_encode_hl_patch(HlPatch self, SseSerializer serializer);

  @protected
  void sse_encode_hl_span(HlSpan self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_js_transform_out(
    JsTransformOut self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_bool(List<bool> self, SseSerializer serializer);

  @protected
  void sse_encode_list_fold_range(
    List<FoldRange> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_hl_line_span(
    List<HlLineSpan> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_hl_span(List<HlSpan> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_hl_patch(
    HlPatch? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_list_fold_range(
    List<FoldRange>? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_list_hl_span(
    List<HlSpan>? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_script_open(ScriptOpen self, SseSerializer serializer);

  @protected
  void sse_encode_script_text_out(ScriptTextOut self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;
}
