// Generate lib/util/build_info.dart with the current pubspec.yaml version and build time.
//
// Usage: run before every `flutter build` / `flutter run`
//   dart run tool/update_build_info.dart

import 'dart:io';

String _two(int n) => n.toString().padLeft(2, '0');

String _fmt(DateTime dt) {
  return '${dt.year}-${_two(dt.month)}-${_two(dt.day)} '
      '${_two(dt.hour)}:${_two(dt.minute)}:${_two(dt.second)}';
}

Future<void> main() async {
  final pubspec = File('pubspec.yaml');
  if (!await pubspec.exists()) {
    stderr.writeln('pubspec.yaml not found (run from the project root)');
    exit(1);
  }
  final lines = await pubspec.readAsLines();
  final versionLine = lines.firstWhere(
    (l) => l.trimLeft().startsWith('version:'),
    orElse: () => '',
  );
  final version = versionLine.split(':').skip(1).join(':').trim();
  if (version.isEmpty) {
    stderr.writeln('pubspec.yaml has no version field');
    exit(1);
  }

  final now = _fmt(DateTime.now());
  final content = '''
// GENERATED by tool/update_build_info.dart — do not edit.
// Run `dart run tool/update_build_info.dart` before each build to refresh.

const String appVersion = '$version';
const String buildTime = '$now';
''';

  final target = File('lib/util/build_info.dart');
  await target.writeAsString(content);
  stdout.writeln('Updated ${target.path}');
  stdout.writeln('  version   = $version');
  stdout.writeln('  buildTime = $now');
}
