// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `build_wasm_hl`, `capture_styles`, `collect_folds`, `doc_edit`, `highlight_static`, `hl_docs_closed`, `hl_docs`, `line_end`, `line_of`, `line_starts_of`, `make_config`, `park_hl`, `park_wasm_hl`, `point_at`, `query_spans`, `run_highlight`, `take_hl`, `take_wasm_hl`, `to_line_spans`, `wasm_failed`, `wasm_pool`, `wasm_sources`, `with_wasm_hl`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `GrammarSrc`, `HlDoc`, `WasmHl`

/// Highlight [source] using the **statically compiled-in** grammar for [lang] (e.g. "json"),
/// returning byte-range spans. Unsupported languages or parse failures return empty (the Dart side
/// falls back to the pure-Dart highlighter).
List<HlSpan> highlight({required String lang, required String source}) =>
    RustLib.instance.api.crateApiHighlightHighlight(lang: lang, source: source);

/// Async variant of [highlight]: flutter_rust_bridge runs it on a worker thread, so highlighting a
/// whole (multi-MB) file does not block the UI isolate. Same result as [highlight].
Future<List<HlSpan>> highlightOffThread({
  required String lang,
  required String source,
}) => RustLib.instance.api.crateApiHighlightHighlightOffThread(
  lang: lang,
  source: source,
);

/// Try loading a WASM grammar and return whether it succeeded. The Dart side uses this at startup
/// to weed out **incompatible** wasm (e.g. built with old emscripten / the old `dylink` format),
/// falling back to static tree-sitter / pure-Dart highlighting instead.
bool wasmGrammarLoads({required String lang, required List<int> wasm}) =>
    RustLib.instance.api.crateApiHighlightWasmGrammarLoads(
      lang: lang,
      wasm: wasm,
    );

/// Register (compile + cache) a **WASM grammar loaded at runtime** (a syntax plugin) under [lang].
/// Pass the grammar's `.wasm` bytes and highlights.scm content **once**; afterwards call
/// [highlight_wasm] with only `(lang, source)`. This avoids marshalling the multi-MB wasm across
/// the FFI boundary on every highlight call (e.g. cpp's wasm is ~5 MB, so doing it per scroll
/// frame / keystroke is what made highlighting lag). Returns whether the grammar built
/// successfully; the result (including failure) is cached, so calling again is cheap.
bool registerWasmGrammar({
  required String lang,
  required List<int> wasm,
  required String query,
}) => RustLib.instance.api.crateApiHighlightRegisterWasmGrammar(
  lang: lang,
  wasm: wasm,
  query: query,
);

/// Highlight [source] with a grammar previously registered via [register_wasm_grammar], looked up
/// by [lang]. Returns empty if the language was never registered or its build failed. Passing only
/// `(lang, source)` keeps each call cheap — the wasm bytes stay in Rust's thread_local cache.
List<HlSpan> highlightWasm({required String lang, required String source}) =>
    RustLib.instance.api.crateApiHighlightHighlightWasm(
      lang: lang,
      source: source,
    );

/// Async variant of [highlight_wasm]: flutter_rust_bridge runs it on a worker thread, so
/// highlighting a whole (multi-MB) file does not block the UI isolate. The grammar must already
/// have been registered via [register_wasm_grammar]; the worker borrows a compiled highlighter
/// from the shared pool (see [with_wasm_hl]) and parks it again when done.
Future<List<HlSpan>> highlightWasmOffThread({
  required String lang,
  required String source,
}) => RustLib.instance.api.crateApiHighlightHighlightWasmOffThread(
  lang: lang,
  source: source,
);

/// Languages **statically compiled into** this backend (lowercase file extension). WASM plugin support is determined by the Dart side's scan.
bool supportedLanguage({required String ext}) =>
    RustLib.instance.api.crateApiHighlightSupportedLanguage(ext: ext);

/// Open an incremental highlighting session for document [id] (replacing any previous session
/// under that id): parse [source] whole and return its byte-range spans (as [highlight] would),
/// keeping the text and syntax tree for later [hl_doc_edit] calls. `None` = the grammar is not
/// available (the caller falls back to window parsing). Runs on a worker thread.
Future<List<HlSpan>?> hlDocOpen({
  required PlatformInt64 id,
  required String lang,
  required bool wasm,
  required String source,
}) => RustLib.instance.api.crateApiHighlightHlDocOpen(
  id: id,
  lang: lang,
  wasm: wasm,
  source: source,
);

/// Replace lines `[start_line, old_end_line)` of session [id] with [new_lines] (line numbering as
/// of the previous call), re-parse incrementally and return the lines whose highlighting must be
/// replaced. `None` = no such session (or the edit was out of range): the caller reopens.
/// Runs on a worker thread; edits of one session must not overlap.
Future<HlPatch?> hlDocEdit({
  required PlatformInt64 id,
  required PlatformInt64 startLine,
  required PlatformInt64 oldEndLine,
  required List<String> newLines,
}) => RustLib.instance.api.crateApiHighlightHlDocEdit(
  id: id,
  startLine: startLine,
  oldEndLine: oldEndLine,
  newLines: newLines,
);

/// Foldable regions of session [id], from its syntax tree (see
/// [collect_folds]); `None` = no such session. Sync: a tree walk, no parse.
List<FoldRange>? hlDocFolds({required PlatformInt64 id}) =>
    RustLib.instance.api.crateApiHighlightHlDocFolds(id: id);

/// Drop session [id] (no-op if there is none).
void hlDocClose({required PlatformInt64 id}) =>
    RustLib.instance.api.crateApiHighlightHlDocClose(id: id);

/// A foldable region: hiding rows `start_row + 1 ..= end_row` collapses it
/// (rows are 0-based lines of the session's source).
class FoldRange {
  final int startRow;
  final int endRow;

  const FoldRange({required this.startRow, required this.endRow});

  @override
  int get hashCode => startRow.hashCode ^ endRow.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FoldRange &&
          runtimeType == other.runtimeType &&
          startRow == other.startRow &&
          endRow == other.endRow;
}

/// One highlighted span within a line, in UTF-16 code units (what Dart's ParagraphBuilder indexes
/// by), so the Dart side needs no text to apply it.
class HlLineSpan {
  final int line;
  final int start;
  final int end;
  final int style;

  const HlLineSpan({
    required this.line,
    required this.start,
    required this.end,
    required this.style,
  });

  @override
  int get hashCode =>
      line.hashCode ^ start.hashCode ^ end.hashCode ^ style.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HlLineSpan &&
          runtimeType == other.runtimeType &&
          line == other.line &&
          start == other.start &&
          end == other.end &&
          style == other.style;
}

/// Result of [hl_doc_edit]: lines `[start_line, end_line)` (new numbering) were re-highlighted;
/// [spans] holds their complete new spans (a line without spans is simply absent).
class HlPatch {
  final PlatformInt64 startLine;
  final PlatformInt64 endLine;
  final List<HlLineSpan> spans;

  const HlPatch({
    required this.startLine,
    required this.endLine,
    required this.spans,
  });

  @override
  int get hashCode => startLine.hashCode ^ endLine.hashCode ^ spans.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HlPatch &&
          runtimeType == other.runtimeType &&
          startLine == other.startLine &&
          endLine == other.endLine &&
          spans == other.spans;
}

/// A single highlight: byte range (within the spliced text) + style id (must align with the Hl in lib/editor/highlight.dart).
class HlSpan {
  final int start;
  final int end;
  final int style;

  const HlSpan({required this.start, required this.end, required this.style});

  @override
  int get hashCode => start.hashCode ^ end.hashCode ^ style.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HlSpan &&
          runtimeType == other.runtimeType &&
          start == other.start &&
          end == other.end &&
          style == other.style;
}
