// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `arm`, `build_ctx`, `build_runner`, `disarm`, `lua_sources`, `lua_string`, `with_script`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `LuaCtx`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `call_hook`, `has`, `transform_lines`, `transform_text`

/// Register (or re-register) a Lua user script under [name]; compiles right
/// here so syntax errors / a missing contract function surface immediately.
/// Returns the error message, or `None` on success.
String? luaRegisterScript({required String name, required String source}) =>
    RustLib.instance.api.crateApiLuaScriptLuaRegisterScript(
      name: name,
      source: source,
    );

/// Drop Lua scripts that are no longer installed (called after a rescan).
void luaRetainScripts({required List<String> names}) =>
    RustLib.instance.api.crateApiLuaScriptLuaRetainScripts(names: names);
