// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `arm`, `build_ctx`, `contract_names`, `disarm`, `err`, `hook_names`, `js_source`, `script_sources`, `session_sender`, `sessions`, `text_budget_ms`, `text_memory_limit`, `with_script`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `Req`, `ScriptCtx`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `call_hook`, `has`, `transform_lines`, `transform_text`

/// Register (or re-register) a user script under [name]. The source is compiled
/// once here to surface syntax errors / a missing contract function
/// immediately. Returns the error message, or `None` on success.
String? jsRegisterScript({required String name, required String source}) =>
    RustLib.instance.api.crateApiScriptJsRegisterScript(
      name: name,
      source: source,
    );

/// Drop scripts that are no longer installed (called after a rescan).
void jsRetainScripts({required List<String> names}) =>
    RustLib.instance.api.crateApiScriptJsRetainScripts(names: names);

/// Open a run of script [name] on [engine] ("js" | "lua"): builds a fresh
/// engine instance on its own thread, evaluates the script and calls its
/// begin hook. On success the returned id serves [script_session_transform_lines]
/// / [script_session_transform_text] until [script_session_close]. Runs on a
/// worker thread (the build can take a moment).
Future<ScriptOpen> scriptSessionOpen({
  required String engine,
  required String name,
}) => RustLib.instance.api.crateApiScriptScriptSessionOpen(
  engine: engine,
  name: name,
);

/// Run the line contract over [lines] on session [id]; [first_line_no] is the
/// 1-based ordinal of `lines[0]` within the processed range. Runs on a worker
/// thread (it blocks until the session thread answers).
Future<JsTransformOut> scriptSessionTransformLines({
  required PlatformInt64 id,
  required List<String> lines,
  required PlatformInt64 firstLineNo,
}) => RustLib.instance.api.crateApiScriptScriptSessionTransformLines(
  id: id,
  lines: lines,
  firstLineNo: firstLineNo,
);

/// Run the whole-text contract on session [id] (the Dart side caps the size).
Future<ScriptTextOut> scriptSessionTransformText({
  required PlatformInt64 id,
  required String text,
}) => RustLib.instance.api.crateApiScriptScriptSessionTransformText(
  id: id,
  text: text,
);

/// End session [id]: the end hook runs and the engine thread exits.
void scriptSessionClose({required PlatformInt64 id}) =>
    RustLib.instance.api.crateApiScriptScriptSessionClose(id: id);

abstract class Runner {
  Future<void> callHook({required String func});

  Future<bool> has({required String func});

  Future<JsTransformOut> transformLines({
    required List<String> lines,
    required PlatformInt64 firstLineNo,
  });

  Future<ScriptTextOut> transformText({required String text});
}

/// Result of one chunked transform call. `error == None` means success:
/// `lines` and `deleted` both have the input's length (`deleted[i]` = the
/// script returned `false` for line i, whose `lines[i]` is then unused).
/// On error both are empty.
class JsTransformOut {
  final List<String> lines;
  final List<bool> deleted;
  final String? error;

  const JsTransformOut({
    required this.lines,
    required this.deleted,
    this.error,
  });

  @override
  int get hashCode => lines.hashCode ^ deleted.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is JsTransformOut &&
          runtimeType == other.runtimeType &&
          lines == other.lines &&
          deleted == other.deleted &&
          error == other.error;
}

/// What [script_session_open] hands back: the session id (valid when
/// `error` is None) and which contract functions the script defines.
class ScriptOpen {
  final PlatformInt64 id;
  final bool hasLine;
  final bool hasText;
  final String? error;

  const ScriptOpen({
    required this.id,
    required this.hasLine,
    required this.hasText,
    this.error,
  });

  @override
  int get hashCode =>
      id.hashCode ^ hasLine.hashCode ^ hasText.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ScriptOpen &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          hasLine == other.hasLine &&
          hasText == other.hasText &&
          error == other.error;
}

/// Result of a whole-text call: `text == None` with no error = unchanged.
class ScriptTextOut {
  final String? text;
  final String? error;

  const ScriptTextOut({this.text, this.error});

  @override
  int get hashCode => text.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ScriptTextOut &&
          runtimeType == other.runtimeType &&
          text == other.text &&
          error == other.error;
}
