// About dialog (Help → About): app name + version. Tapping the version number
// toggles the build time from lib/util/build_info.dart (a file GENERATED by
// `dart run tool/update_build_info.dart` — run it before a build to stamp it).

import 'package:flutter/material.dart';
import 'package:url_launcher/url_launcher.dart';

import '../l10n/app_localizations.dart';
import '../util/build_info.dart';

/// Project home page shown (and opened) from the About dialog.
const String projectUrl = 'https://github.com/madedit/madedit2';

Future<void> showAppAboutDialog(BuildContext context) => showDialog<void>(
  context: context,
  builder: (_) => const AboutAppDialog(),
);

class AboutAppDialog extends StatefulWidget {
  const AboutAppDialog({super.key});

  @override
  State<AboutAppDialog> createState() => _AboutAppDialogState();
}

class _AboutAppDialogState extends State<AboutAppDialog> {
  bool _showBuildTime = false;

  @override
  Widget build(BuildContext context) {
    final l10n = AppLocalizations.of(context);
    return AlertDialog(
      title: Row(
        children: [
          // Bundled render of assets/icons/madedit2.svg (flutter has no
          // native SVG rendering; the PNG is the same art).
          Image.asset(
            'assets/icons/madedit2.png',
            width: 40,
            height: 40,
            filterQuality: FilterQuality.medium,
          ),
          const SizedBox(width: 12),
          const Text('madedit2'),
        ],
      ),
      content: Column(
        mainAxisSize: MainAxisSize.min,
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          // One-line description: free and open source, large files.
          Padding(
            padding: const EdgeInsets.only(bottom: 8),
            child: Text(l10n.tr('about_tagline')),
          ),
          InkWell(
            onTap: () => setState(() => _showBuildTime = !_showBuildTime),
            child: Padding(
              padding: const EdgeInsets.symmetric(vertical: 4),
              child: Text(l10n.trf('about_version', [appVersion])),
            ),
          ),
          if (_showBuildTime)
            Padding(
              padding: const EdgeInsets.only(top: 4),
              child: Text(
                l10n.trf('about_build_time', [buildTime]),
                style: Theme.of(context).textTheme.bodySmall,
              ),
            ),
          const SizedBox(height: 8),
          // Project home page: opens in the system browser.
          InkWell(
            onTap: () => launchUrl(
              Uri.parse(projectUrl),
              mode: LaunchMode.externalApplication,
            ),
            child: Padding(
              padding: const EdgeInsets.symmetric(vertical: 4),
              child: Text(
                projectUrl,
                style: TextStyle(
                  color: Theme.of(context).colorScheme.primary,
                  decoration: TextDecoration.underline,
                ),
              ),
            ),
          ),
        ],
      ),
      actions: [
        TextButton(
          onPressed: () => Navigator.of(context).pop(),
          child: Text(l10n.tr('common_close')),
        ),
      ],
    );
  }
}
