import 'dart:convert';
import 'dart:io';

import 'package:flutter/widgets.dart';
import 'package:flutter/services.dart' show rootBundle;

import '../settings/config_loader.dart';
import '../util/log.dart';

/// Source of localized strings for the menubar (and the rest of the UI).
///
/// Design: uses the **standard ARB format** (external
/// `settings/l10n/app_<locale>.arb` first, falling back to the bundled
/// `assets/l10n/`, see [loadConfigString]) but **loaded at runtime** into a
/// dictionary rather than strongly-typed getters generated by gen-l10n --
/// menus are defined dynamically in JSON and reference translations by
/// string key (`labelKey`), which needs a dynamic `tr(key)` lookup that
/// gen-l10n's static getters cannot provide.
///
/// It still plugs into Flutter's `Localizations` mechanism (via [delegate]),
/// so as soon as the locale changes `AppLocalizations.of(context)` returns the
/// new language and the text switches live after the rebuild.
class AppLocalizations {
  AppLocalizations(this.locale, this._strings);

  final Locale locale;
  final Map<String, String> _strings;

  /// Dynamic lookup of the translation for a key; returns the key itself when
  /// missing (so a missing translation is obvious at a glance).
  String tr(String key) => _strings[key] ?? key;

  /// [tr] with positional placeholders: `{0}`, `{1}`, … replaced by [args].
  String trf(String key, List<Object?> args) {
    var s = tr(key);
    for (var i = 0; i < args.length; i++) {
      s = s.replaceAll('{$i}', '${args[i]}');
    }
    return s;
  }

  static AppLocalizations of(BuildContext context) =>
      Localizations.of<AppLocalizations>(context, AppLocalizations)!;

  /// The most recently loaded instance — for strings built without a
  /// BuildContext (tab names, controller-facing text). Widgets should prefer
  /// [of] so they rebuild on locale changes.
  static AppLocalizations? current;

  /// Context-free lookup via [current]; returns the key before any load.
  static String t(String key) => current?.tr(key) ?? key;

  /// Context-free [trf].
  static String tf(String key, List<Object?> args) =>
      current?.trf(key, args) ?? key;

  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();

  /// UI languages, DISCOVERED by [discover] from the `.arb` files: bundled
  /// `assets/l10n/app_<tag>.arb` plus external `settings/l10n/app_<tag>.arb`
  /// — dropping a new file in either place adds the language, no code change
  /// (the language menu, the settings value and locale resolution all come
  /// from this list). **en first**: MaterialApp's default resolution falls
  /// back to the first entry when nothing matches.
  ///
  /// The initial value is only a seed for tests, which build a MaterialApp
  /// with this list without running main(); the app replaces it at startup.
  static List<Locale> supportedLocales = <Locale>[
    const Locale('en'),
    const Locale('zh', 'TW'),
    const Locale('ja'),
    const Locale('ar'),
  ];

  /// Native display name of each language (the `lang_name` string inside its
  /// own ARB: "正體中文", "日本語"…), keyed by [tagOf]. Filled by [discover];
  /// a file without the key shows its tag.
  static Map<String, String> nativeNames = {};

  /// locale → settings tag / .arb file key: `language_COUNTRY` (zh_TW) or a bare language code.
  static String tagOf(Locale locale) => locale.countryCode != null
      ? '${locale.languageCode}_${locale.countryCode}'
      : locale.languageCode;

  /// Native name for the language menu.
  static String nativeNameOf(Locale l) => nativeNames[tagOf(l)] ?? tagOf(l);

  /// Settings tag → the supported locale it means, or null for '' / unknown
  /// (= follow the system). A bare language matches its regional file
  /// ('zh' → zh_TW, the pre-tag menu action), a regional tag with no exact
  /// file matches its language ('zh_HK' → zh_TW).
  static Locale? localeFor(String tag) {
    if (tag.isEmpty) return null;
    final parts = tag.split('_');
    final lang = parts[0], country = parts.length > 1 ? parts[1] : null;
    Locale? exact(String l, String? c) {
      for (final s in supportedLocales) {
        if (s.languageCode == l && s.countryCode == c) return s;
      }
      return null;
    }
    final hit = exact(lang, country);
    if (hit != null) return hit;
    if (lang == 'zh') {
      // Chinese splits by script, not by "any zh": a Traditional region (or
      // the bare 'zh' of the old lang.zh menu action) prefers zh_TW / HK / MO,
      // a Simplified one zh_CN / SG — alphabetical order would hand zh_HK
      // to zh_CN.
      final traditional =
          country == null || const {'TW', 'HK', 'MO', 'Hant'}.contains(country);
      final prefer = traditional
          ? const ['TW', 'HK', 'MO', 'CN', 'SG']
          : const ['CN', 'SG', 'TW', 'HK', 'MO'];
      for (final c in prefer) {
        final l = exact('zh', c);
        if (l != null) return l;
      }
    }
    for (final l in supportedLocales) {
      if (l.languageCode == lang) return l;
    }
    return null;
  }

  /// Best supported match for a requested locale: language+country →
  /// language → English.
  static Locale resolve(Locale locale) =>
      localeFor(tagOf(locale)) ?? const Locale('en');

  static final RegExp _arbName = RegExp(r'^app_([a-z]{2,3}(?:_[A-Za-z]{2,4})?)\.arb$');

  /// Scan the bundled and external `l10n/` directories for `app_<tag>.arb`
  /// files and read each one's `lang_name`; replaces [supportedLocales] and
  /// [nativeNames]. Called once in main() before runApp; the external
  /// directory may not exist (fresh install, tests).
  static Future<void> discover() async {
    final tags = <String>{};
    final bundled = <String>{};
    for (final a in await listBundledAssets('assets/l10n/')) {
      final m = _arbName.firstMatch(a.substring('assets/l10n/'.length));
      if (m != null) {
        tags.add(m.group(1)!);
        bundled.add(m.group(1)!);
      }
    }
    final external = <String, File>{};
    try {
      final dir = Directory(settingsPath('l10n'));
      if (await dir.exists()) {
        await for (final e in dir.list()) {
          if (e is! File) continue;
          final m = _arbName.firstMatch(e.uri.pathSegments.last);
          if (m != null) {
            tags.add(m.group(1)!);
            external[m.group(1)!] = e;
          }
        }
      }
    } catch (e) {
      Log.instance.w('l10n: cannot list external l10n directory ($e)');
    }
    if (tags.isEmpty) return; // keep the seed rather than an empty list
    final sorted = tags.toList()
      ..sort((a, b) {
        if (a == 'en') return -1;
        if (b == 'en') return 1;
        return a.compareTo(b);
      });
    final names = <String, String>{};
    for (final tag in sorted) {
      String? name;
      if (bundled.contains(tag)) {
        try {
          name = _langName(await rootBundle.loadString('assets/l10n/app_$tag.arb'));
        } catch (_) {}
      }
      final ext = external[tag];
      if (ext != null) {
        try {
          name = _langName(await ext.readAsString()) ?? name;
        } catch (_) {}
      }
      if (name != null) names[tag] = name;
    }
    supportedLocales = [
      for (final t in sorted)
        t.contains('_')
            ? Locale(t.split('_')[0], t.split('_')[1])
            : Locale(t),
    ];
    nativeNames = names;
    Log.instance.mark(
      'l10n languages discovered (${sorted.join(', ')}; external: ${external.keys.join(', ')})',
    );
  }

  static String? _langName(String raw) {
    try {
      final v = (jsonDecode(raw) as Map)['lang_name'];
      return v is String && v.trim().isNotEmpty ? v.trim() : null;
    } catch (_) {
      return null;
    }
  }
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  // Accept everything: load() resolves to the closest supported locale and
  // falls back to English, so an unknown system locale still gets strings.
  @override
  bool isSupported(Locale locale) => true;

  @override
  Future<AppLocalizations> load(Locale locale) async {
    // Best supported match: language+country → language → English.
    final match = AppLocalizations.resolve(locale);
    final fileKey = AppLocalizations.tagOf(match);
    // Start from the bundled strings and let the external file override them,
    // key by key. settings/l10n/ is seeded once and never overwritten, so a
    // straight "external replaces bundled" would leave every string added
    // after the user's first launch untranslated — tr() falls back to the key
    // itself, so new menu items would literally read "item_print".
    // A language that exists only as an external file (user-added) has no
    // bundled base: English underneath, so its missing keys read English.
    final strings = <String, String>{};
    try {
      strings.addAll(
        _arbStrings(await rootBundle.loadString('assets/l10n/app_$fileKey.arb')),
      );
    } catch (_) {
      strings.addAll(
        _arbStrings(await rootBundle.loadString('assets/l10n/app_en.arb')),
      );
    }
    strings.addAll(_arbStrings(await loadConfigString('l10n/app_$fileKey.arb')));
    Log.instance.mark('l10n loaded ($fileKey)');
    return AppLocalizations.current = AppLocalizations(match, strings);
  }

  /// The real strings in an ARB: `@@locale` and `@key` metadata are skipped.
  static Map<String, String> _arbStrings(String raw) {
    final out = <String, String>{};
    try {
      final json = (jsonDecode(raw) as Map).cast<String, dynamic>();
      for (final e in json.entries) {
        if (e.key.startsWith('@')) continue;
        final v = e.value;
        if (v is String) out[e.key] = v;
      }
    } catch (_) {
      // A corrupt external file simply contributes nothing; the bundled base
      // (loaded first) still stands.
    }
    return out;
  }

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}
